[BE] create register component
unmsmfisi-socialapplication/social_app pull request #121
Opened 2023-09-08 18:30 UTC by miguel1808

Introduced new user and password hash functions using bcrypt

UserRepository interface was established to insert new users into the database

Use case for user verification by email to validate that multiple accounts are not created with the same email

The registerUserHandler handler was developed to send HTTP registration requests,

2023-09-29 04:26 UTC, luzelenatt commented
@AngelGio

2023-10-04 02:24 UTC, ekimike requested changes

2023-10-04 02:24 UTC, ekimike commented on backend/internal/register/application/registerUseCase.go
> +	ErrInvalidCredentials = errors.New("credenciales inválidas")
You meant:
user not found
invalid credentials

2023-10-04 02:24 UTC, ekimike commented on backend/internal/register/application/registerUseCase.go
> +		return nil, errors.New("el nombre de usuario ya está en uso")
You meant:

the username is already in use

2023-10-04 02:24 UTC, ekimike commented on backend/internal/register/infrastructure/userRepository.go
> +	fmt.Println("Insertando usuario en la base de datos...")
Whenever is needed to track down our actions, it should be better to use a logging library.

2023-10-04 02:24 UTC, ekimike commented on backend/internal/register/infrastructure/userRepository.go
> +		return nil, errors.New("el correo electrónico ya está en uso")
you meant?:

email is already in use

2023-10-04 02:24 UTC, ekimike commented on backend/internal/register/infrastructure/userRepository.go
> +		fmt.Println("Error al iniciar la transaccion")
You meant:

Error while starting the transaction

2023-10-05 01:14 UTC, AngelGio commented
@miguel1808 The HTTP status code in the TestRegisterUserHandler_RegisterUser_Success test case should be 201 Created instead of 200 OK. The HTTP status code 201 Created is more appropriate for indicating that a resource has been successfully created, which aligns with the registration of a new user. Please update the test to use http.StatusCreated for a more accurate representation of the expected HTTP status code.

2023-10-20 21:57 UTC, LuiggiPasacheL approved these changes

2023-10-20 22:00 UTC, ekimike approved these changes

2023-10-20 22:00 UTC, merged