I have created the 'validatePassword' function
unmsmfisi-socialapplication/social_app pull request #341
Opened 2023-10-05 19:30 UTC by Artanis7488

In this code, I have created a password validation function and written tests to verify its functionality.

In "constant.tsx," I have defined a constant: "passwordCompare" (an error message in case of non-matching passwords).

In "Functions.tsx," I have created the "validatePasswords" function that compares two passwords and returns an error message or "null" if they match.

In "function.test.tsx," I have used Jest to write two tests: the first one checks that the function returns "null" if the passwords match, and the second one checks that it returns the error message if they don't match.

2023-10-06 00:04 UTC, ekimike requested changes

2023-10-06 00:04 UTC, ekimike commented on frontend/src/utilities/Functions.tsx
> +      return null; // Las contraseñas coinciden
Why are you returning a null value when the comparison was successful on a method which its name suggests to perform a validation, which should result a boolean value, TRUE when success and FALSE when wrong.

2023-10-06 00:04 UTC, ekimike commented on frontend/src/utilities/Functions.tsx
> +      return passwordCompare;
Image being a new developer on this team who reads this piece of code, what do you think him/her will infer based on the name `passwordCompare`?  It seems more to a method name than a result.

2023-10-06 05:26 UTC, AnthonyRicse98 approved these changes

2023-10-06 05:30 UTC, Anthonyricse approved these changes

2023-10-06 05:51 UTC, Artanis7488 commented on frontend/src/utilities/Functions.tsx
> +export function validarContraseñas(contraseña1: string, contraseña2: string): string | null {
I already switched it to the English version.

2023-10-06 05:53 UTC, Artanis7488 commented on frontend/src/utilities/Functions.tsx
> +      return null; // Las contraseñas coinciden
You're right, now it returns true or false.

2023-10-06 05:55 UTC, Artanis7488 commented on frontend/src/utilities/Constant.tsx
> +export const passwordCompare = 'Las contraseñas no coinciden';
Done, professor. I've already changed the name to 'passwordMismatchError'

2023-10-06 18:53 UTC, Artanis7488 commented on frontend/src/test/function.test.tsx
> +    const contraseña2 = 'otracontraseña';
I already changed it into English, professor.

2023-10-06 18:54 UTC, Artanis7488 commented on frontend/src/test/function.test.tsx
> +    const contraseña2 = 'contraseña123';
I already changed it into English, professor.

2023-10-07 14:29 UTC, ekimike approved these changes

2023-10-08 05:30 UTC, merged