[BE]: Feat - Implementation of Multiposting in Mastodon and Pixelfed
unmsmfisi-socialapplication/social_app pull request #391
Opened 2023-10-07 02:22 UTC by Adrianabalcd

**Description of Changes:**
This Pull Request represents the first part of the technical implementation of the multiposting feature in our application. The technical changes made are as follows:

**PostHandler Controller (Post Controller):**
- Expanded the controller to support the creation and posting of posts on multiple social networks, with a focus on Mastodon and Pixelfed.
- Implemented additional logic to format and send data to the Mastodon and Pixelfed APIs.

**PostUseCase (Post Use Case):**
- Modifications to handle multiposting in Mastodon and Pixelfed.
- Addition of methods and logic to orchestrate the creation and posting on specific social networks.

**Data Structures:**

- Added new data structures to represent posts in Mastodon and Pixelfed, including fields specific to each social network.
- Updates to the CreatePost structure to include optional fields for Mastodon and Pixelfed, allowing for customization of posts on these networks.

2023-10-07 04:27 UTC, felixalfonsofernandez approved these changes

2023-10-13 21:16 UTC, eds000n requested changes
how does mastodon allow us to post in the network? I assume there's some API keys that are needed, how do we handle them? also please add tests

2023-10-13 21:16 UTC, eds000n commented on backend/internal/post/infrastructure/postHandler.go
> +    // if requestData.MastodonData != nil {
why is the commented?

2023-11-01 18:22 UTC, Adrianabalcd commented on backend/internal/post/infrastructure/postHandler.go
> +    // if requestData.MastodonData != nil {
I made the comments because this implementation was a general advance in terms of functionality and I left guides in some parts to be able to continue with the implementation. I will take into account what was mentioned in relation to Mastodon and the management of API keys as well as the tests, thank you very much for your instructions.

2023-11-03 19:29 UTC, closed without merging